### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by jzmaddock**

### CODE REVIEW

**Comment by jzmaddock** [comment]
This builds on #83 by adding CI based on that used by Boost.Config.

**Comment by jzmaddock** [comment]
OK, we now have pretty decent CI coverage in this PR, unless someone objects (@swatanabe ?) I'll probably go on ahead and merge.

**Comment by jwakely** [comment]
Could the fixes for the tests please be merged to `master` so they make it into a release one day?

**Comment by mborland** [comment]
> Could the fixes for the tests please be merged to `master` so they make it into a release one day?

Yes. I'll make sure it makes the next release.

**Pull request merged**
