### PR TITLE
Conditionally replace deprecated/removed C++98 std::bind2nd by std::b…

### PR DESCRIPTION
**Pull request by DanielaE**
…ind, and std::random_shuffle by an adapted std::shuffle.

Signed-off-by: Daniela Engert <dani@ngrt.de>

### CODE REVIEW

**Comment by jzmaddock** [comment]
> > M test/test_old_uniform_int_distribution.cpp (39)
> > M test/test_random_number_generator.cpp (38)
> >
>
> Adapting these to use std::shuffle makes no sense,
> because they are specifically testing compatibility
> with std::random_shuffle. If std::random_shuffle
> doesn't exist, there's no point to these tests and
> they can just be #ifdef'ed out entirely.
>

FYI we have |BOOST_NO_CXX98_RANDOM_SHUFFLE for just that purpose.

HTH, John.
|

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by DanielaE** [comment]
Steve, I hope you like this more!
John, of course ...

**Comment by swatanabe** [comment]
AMDG

On 05/13/2017 11:04 AM, Daniela Engert wrote:
> Steve, I hope you like this more!
> John, of course ...
> 

  The random_shuffle changes look good, but
in C++03, a local class cannot be a template
parameter.

In Christ,
Steven Watanabe

**Comment by DanielaE** [comment]
Steve, thx for this info - never heard about that before. Then I am probably going to make Sean unhappy ...

**Pull request merged**
