### PR TITLE
Multiprecision support in Boost.Random

### PR DESCRIPTION
**Pull request by jzmaddock**
This is the revised patches with reduced commit history.

### CODE REVIEW

**Comment by swatanabe** [comment]
Manually closing this, since it's actually against develop not master.

**Comment by jzmaddock** [comment]
Thanks for merging that - and your patience - one of these days I'll actually understand git ;(

**Comment by jzmaddock** [comment]
Any chance of these changes being merged to master?

Current test results look good, and it's getting increasingly tricky to keep cherry-picking from multiprecision develop when I can't do a full merge :(

Thanks, John.

**Comment by jzmaddock** [comment]
Ping?

**Pull request closed without merging**
