### PR TITLE
Added constexpr support to min/max functions of random number generators. Fixes #12251

### PR DESCRIPTION
**Pull request by gblanco92**
This fixes https://svn.boost.org/trac/boost/ticket/12251

### CODE REVIEW

**Comment by mclow** [comment]
The code changes look good, but there's no tests!

**Comment by gblanco92** [comment]
I will add tests for this!

**Comment by mclow** [comment]
Ping?

**Comment by rtimmons** [comment]
Is there any way to get this merged?

I've got a project that wants to use cross-platform `std::stuffle` and the lack of `constexpr min()` and `constexpr max()` on `boost::random::mt19937_64` and friends leads to compiler errors

```
.../usr/include/c++/v1/algorithm:2950:57: error:
  constexpr variable '_Rp' must be initialized by a constant expression
    static _LIBCPP_CONSTEXPR const _Working_result_type _Rp = _Engine::max() - _Engine::min()
```

I've verified that this change fixes the compiler error at least for my limited selection of platforms (latest gcc and clang on osx and a few linuxes).

**Comment by mclow** [comment]
Still has no tests....

**Comment by rtimmons** [comment]
Thanks @mclow - do you have any input on how this should be tested to satisfaction?

-   My instincts say it's enough to e.g. assert `additive_combine::min()` (and similar) can be evaluated in a constexpr context. 

    Is there a way to do this that respects the `BOOST_CONSTEXPR` macro? Is it sufficient to rely on the `_NO_*_CONSTEXPR` defs?

    ```c++
    #if !defined(BOOST_NO_CXX11_CONSTEXPR) && !defined(BOOST_NO_CXX14_CONSTEXPR)
    // test that xyz::min(),xyz::max() can be evaluated in constexpr context
    #endif
    ```

- Alternatively we could assert that `std::shuffle` or other STL algorithms work with these RNGs. But that may not be direct enough for this and/or depends on a particular STL requiring `min/max` to be `constexpr` (which [the reference](https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator) doesn't actually seem to require)

**Comment by mclow** [comment]
> My instincts say it's enough to e.g. assert additive_combine::min() (and similar) can be evaluated in a constexpr context.

Can they be evaluated, and do they return a sane answer.
`static_assert` is probably your friend here.

**Pull request closed without merging**
