### PR TITLE
add BOOST_PREVENT_MACRO_SUBSTITUTION() to min,max

### PR DESCRIPTION
**Pull request by kotika**
Fix https://github.com/boostorg/math/issues/468 which is in turn caused by the collision in minwindef.h on Windows.h

### CODE REVIEW

**Comment by NAThompson** [comment]
@swatanabe: This is breaking a lot of builds throughout the boost project; do you mind taking a look?

**Comment by NAThompson** [comment]
@kotika : Do you understand the merge conflict?

**Comment by mborland** [comment]
@kotika: the merge conflict looks to be stemming from your branch of develop missing https://github.com/boostorg/random/commit/f5c6c6bacffcf9c14ff7c492b9af115fe516172b.

**Comment by mborland** [comment]
PR #80 encompasses these changes as well as others throughout random.

**Comment by swatanabe** [comment]
This was subsumed by #80 which has been merged

**Pull request closed without merging**
